
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/home/hx/.conda/envs/vllm-py310/lib/python3.10/site-packages/cmake/data/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/local/cuda/bin/"
      - "/home/hx/.local/bin/"
      - "/home/hx/.conda/envs/vllm-py310/bin/"
      - "/opt/conda/condabin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/home/hx/.dotnet/tools/"
    searched_directories:
      - "/usr/local/cuda/bin/uname"
      - "/home/hx/.local/bin/uname"
      - "/home/hx/.conda/envs/vllm-py310/bin/uname"
      - "/opt/conda/condabin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/usr/local/cuda/bin"
        - "/home/hx/.local/bin"
        - "/home/hx/.conda/envs/vllm-py310/bin"
        - "/opt/conda/condabin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/home/hx/.dotnet/tools"
  -
    kind: "message-v1"
    backtrace:
      - "/home/hx/.conda/envs/vllm-py310/lib/python3.10/site-packages/cmake/data/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-181-generic - x86_64
...
